### PR TITLE
adding Norsk and Svenska languages, removed hebrew language by comment

### PR DESCRIPTION
**Pull request by zaherkassem**

### CODE REVIEW

**Comment by karencwix** [comment]
Why did you remove hebrew?

**Comment by zaherkassem** [comment]
according the email from Noam Moravtcik "HE which is not an official Wix language"

**Comment by karencwix** [comment]
Noam does not own this product :)

If you do not want to support the the Hebrew language in your application, please use your own branch. Do not change the framework

**Comment by zaherkassem** [comment]
Adding Dansk langauge & return He.
add all new languages to test languagePicker.js

**Comment by tautvilas** [comment]
waiting for merge

**Pull request merged**
